"""learning_session_periods"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector.sqlalchemy


revision = '3dc1cfb56e62'
down_revision = '48496885fc84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learningsession',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('path_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('node_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_active_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['node.id'], ),
    sa.ForeignKeyConstraint(['path_id'], ['learningpath.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['thread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learningsession_path_id'), 'learningsession', ['path_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learningsession_path_id'), table_name='learningsession')
    op.drop_table('learningsession')
    # ### end Alembic commands ###
